import { mkdirSync, writeFileSync, cpSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export interface GeneratePaidServerOptions {
  readonly openapiPath: string;
  readonly outDir: string;
  readonly pricesPath?: string;
  readonly upstreamBaseUrl?: string;
  readonly allowlist?: readonly string[];
}

/**
 * Generate a runnable paid MCP server package into outDir.
 * The generated server loads env at runtime and uses FacilitatorSettler.
 */
export function generatePaidServer(options: GeneratePaidServerOptions): void {
  const out = resolve(options.outDir);
  mkdirSync(out, { recursive: true });
  mkdirSync(join(out, "src"), { recursive: true });

  const openapiDest = join(out, "openapi.yaml");
  cpSync(resolve(options.openapiPath), openapiDest);

  let pricesRelative: string | undefined;
  if (options.pricesPath !== undefined) {
    const dest = join(out, "prices.yaml");
    cpSync(resolve(options.pricesPath), dest);
    pricesRelative = "./prices.yaml";
  }

  const pkg = {
    name: "paid-mcp-server",
    private: true,
    type: "module",
    version: "0.1.0",
    scripts: {
      start: "node ./src/server.js",
      build: "echo 'prebuilt'",
    },
    dependencies: {
      "openapi-to-paymcp": "latest",
    },
  };
  writeFileSync(join(out, "package.json"), `${JSON.stringify(pkg, null, 2)}\n`);

  const allowlistJson = JSON.stringify(options.allowlist ?? []);
  const upstream = options.upstreamBaseUrl ?? "";
  const pricesLine =
    pricesRelative !== undefined
      ? `const pricesPath = fileURLToPath(new URL("${pricesRelative}", import.meta.url));`
      : "const pricesPath = undefined;";

  const serverSrc = `#!/usr/bin/env node
import { fileURLToPath } from "node:url";
import {
  loadConfigFromEnv,
  loadOpenApi,
  compileOperations,
  defaultUpstreamBase,
  buildPriceTable,
  loadPricesFile,
  runPaidMcpStdio,
} from "openapi-to-paymcp";

const openapiPath = fileURLToPath(new URL("./openapi.yaml", import.meta.url));
${pricesLine}
const allowlist = ${allowlistJson};
const upstreamOverride = ${JSON.stringify(upstream)};

const config = loadConfigFromEnv();
const doc = loadOpenApi(openapiPath);
const operations = compileOperations(doc);
const pricesFile = pricesPath !== undefined ? loadPricesFile(pricesPath) : undefined;
const prices = buildPriceTable(operations, pricesFile);
const upstreamBaseUrl =
  upstreamOverride.length > 0 ? upstreamOverride : defaultUpstreamBase(doc);

await runPaidMcpStdio({
  config,
  operations,
  prices,
  upstreamBaseUrl,
  allowlist: allowlist.length > 0 ? allowlist : undefined,
});
`;

  writeFileSync(join(out, "src/server.js"), serverSrc);

  const envExample = `# Real x402 facilitator settlement — required
PAYMCP_FACILITATOR_URL=https://x402.org/facilitator
PAYMCP_PAY_TO=0xYourRecipientAddress
PAYMCP_NETWORK=eip155:84532
PAYMCP_ASSET=0x036CbD53842c5426634e7929541eC2318f3dCF7e

# Optional (CDP production facilitator — Base mainnet)
# PAYMCP_FACILITATOR_URL=https://api.cdp.coinbase.com/platform/v2/x402
# PAYMCP_FACILITATOR_AUTH_TOKEN=Bearer eyJ...
# CDP_API_KEY_ID=
# CDP_API_KEY_SECRET=

# Optional
# PAYMCP_ASSET_NAME=USDC
# PAYMCP_MAX_TIMEOUT_SECONDS=60
# PAYMCP_SCHEME=exact
# PAYMCP_LEDGER_PATH=./paymcp-ledger.db
# PAYMCP_DATABASE_URL=postgres://user:pass@localhost:5432/paymcp
# PAYMCP_FACILITATOR_TIMEOUT_MS=15000
# PAYMCP_FACILITATOR_MAX_RETRIES=2
# PAYMCP_RATE_LIMIT_MAX=60
# PAYMCP_RATE_LIMIT_WINDOW_MS=60000
`;
  writeFileSync(join(out, ".env.example"), envExample);

  const readme = `# Generated paid MCP server

Generated by \`paymcp\` from an OpenAPI spec.

## Run

1. Copy \`.env.example\` to \`.env\` and set facilitator + pay-to values.
2. Ensure the upstream API from the OpenAPI \`servers\` URL is running.
3. \`node ./src/server.js\` (stdio MCP).

Settlement uses the real HTTP facilitator at \`PAYMCP_FACILITATOR_URL\`
(\`/verify\` + \`/settle\`). There is no simulated payment mode.
`;
  writeFileSync(join(out, "README.md"), readme);

  void dirname;
  void fileURLToPath;
  void existsSync;
}

export function bootPaidServerFromSpec(options: {
  readonly openapiPath: string;
  readonly pricesPath?: string;
  readonly upstreamBaseUrl?: string;
  readonly allowlist?: readonly string[];
}): void {
  // Dynamic import path used by CLI --serve
  void options;
}
